version: '3'
networks:
   proxy_merge:
     external: true

services:
  proxy_merge:
    image: proxy_merge
    env_file:
      - ./.env
    restart: always  # 配置容器自动重启
    ports:
      - "34567:8000"
    networks:
      - proxy_merge